CREATE SCHEMA IF NOT EXISTS geneWorld;

CREATE USER apiRest WITH PASSWORD 'P@ssw0rd';

GRANT CONNECT ON DATABASE apocalypseMilitary2391 TO apiRest;

GRANT USAGE ON SCHEMA geneWorld TO apiRest;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA geneWorld TO apiRest;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA geneWorld TO apiRest;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA geneWorld TO apiRest;

GRANT ALL PRIVILEGES ON DATABASE apocalypseMilitary2391 TO apiRest;

ALTER USER apiRest CREATEDB;

ALTER USER apiRest WITH SUPERUSER;


CREATE TABLE users
(
    id SERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
)