-- USER
CREATE USER apirest WITH PASSWORD 'P@ssw0rd';

GRANT CONNECT ON DATABASE apocalypsemilitary2391 TO apirest;

GRANT USAGE ON SCHEMA geneWorld TO apirest;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA geneWorld TO apirest;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA geneWorld TO apirest;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA geneWorld TO apirest;

GRANT ALL PRIVILEGES ON DATABASE apocalypsemilitary2391 TO apirest;

ALTER USER apirest CREATEDB;

ALTER USER apirest WITH SUPERUSER;

-- EXTENSIONS
CREATE EXTENSION pgcrypto;
