-- USER
CREATE USER zlkuzomxmuorww WITH PASSWORD 'P@ssw0rd';

GRANT CONNECT ON DATABASE d8gbunth16quu8 TO zlkuzomxmuorww;

GRANT USAGE ON SCHEMA geneWorld TO zlkuzomxmuorww;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA geneWorld TO zlkuzomxmuorww;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA geneWorld TO zlkuzomxmuorww;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA geneWorld TO zlkuzomxmuorww;

GRANT ALL PRIVILEGES ON DATABASE d8gbunth16quu8 TO zlkuzomxmuorww;

ALTER USER zlkuzomxmuorww CREATEDB;

ALTER USER zlkuzomxmuorww WITH SUPERUSER;

-- EXTENSIONS
CREATE EXTENSION pgcrypto;
